import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import AuroraBackground from "@/components/aurora-background"; // Import AuroraBackground

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased relative`}>
          {/* Aurora Background */}
          <AuroraBackground>{children}</AuroraBackground>
          {/* Content */}
          <div className="relative z-10">{children}</div>

          <GoogleOneTap />
        </body>
      </html>
    </ClerkProvider>
  );
}
