// RootLayout.js or your layout component
import { Inter } from "next/font/google";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider suppressHydrationWarning>
      <div className={`${inter.variable} antialiased`}>
        {children}
        <GoogleOneTap />
      </div>
    </ClerkProvider>
  );
}
