import { Inter } from "next/font/google";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import Layout from "@/components/Layout"; // Import the Layout component
import "@/styles/globals.css"; // Import the global CSS (replacing ./globals.css)

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      navigateAfterSignIn="/dashboard"
      navigateAfterSignUp="/dashboard"
      clockSkewInSeconds={60}
    >
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          <ReactQueryProvider>
            <Layout>
              {" "}
              {/* Wrap children with Layout */}
              {children}
            </Layout>
            <GoogleOneTap />
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
