import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import Layout from "@/app/_components/components/Layout";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Zora",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      signInUrl="/sign-in"
      signUpUrl="/sign-up"
      navigateAfterSignIn="/dashboard"
      navigateAfterSignUp="/dashboard"
      clockSkewInSeconds={60}
    >
      <html lang="en">
        <body className={`${inter.variable} antialiased bg-[#2D3345]`}>
          <ReactQueryProvider>
            <Layout>{children}</Layout>
            <GoogleOneTap />
          </ReactQueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
